#!/usr/bin/env bash

# .zshrc - z shell configuration
# =========================================================
# - https://github.com/danishprakash/dotfiles
# - danishpraka.sh

# Firefox
ctrl + cmd - f : open -a firefox

# iTerm
ctrl + cmd - a : open -a iTerm

# Slack
# ctrl + cmd - s: osascript /Users/danish/programming/dotfiles/firefox_open_slack
ctrl + cmd - s: open -a Slack

# Zoom
ctrl + cmd - m: open -a zoom.us

# Notion
# ctrl + cmd - n: open -a Notion
ctrl + cmd - n: osascript /Users/danish/programming/dotfiles/firefox_open_pinned_tab

# Preview (PDF viewer)
ctrl + cmd - p: open -a Preview

# Anki
ctrl + cmd - r: open -a Anki\ 2
