#!/usr/bin/env bash

# .zshrc - z shell configuration
# =========================================================
# - https://github.com/danishprakash/dotfiles
# - danishpraka.sh

# Firefox
ctrl + cmd - f : open -a firefox

# iTerm
ctrl + cmd - a : open -a iTerm

# Slack
ctrl + cmd - s: open -a Slack

# Zoom
ctrl + cmd - m: open -a zoom.us

# Notion
ctrl + cmd - n: open -a Notion

# Preview (PDF viewer)
ctrl + cmd - p: open -a Preview
