#!/bin/bash

# battery - print battery level with charging indicator

output=$(pmset -g batt)
source=$(echo ${output} | grep -Eo "AC" &> /dev/null && echo "$?")
level=$(echo ${output} | grep -Eo "\d+%" | cut -d% -f1)%

if [[ "${source}" == "0" ]]; then
    echo "*${level}"
else
    echo "${level}"
fi
