#!/bin/bash

# battery - print battery level with charging indicator

output=$(pmset -g batt)
source=$(echo ${output} | grep -Eo "AC" &>/dev/null && echo "$?")
level=$(echo ${output} | grep -Eo "\d+%" | cut -d% -f1)

if [[ "${source}" == "0" ]]; then
    echo "+${level}"
else
    if [[ ! -z "$TMUX_STATUSLINE" ]]; then
        if [[ ${level} -lt 15 ]]; then
            echo -e "#[fg=colour001]${level}%#[fg=color1]"
        else
            echo -e "#[fg=colour237]${level}%#[fg=color1]"
        fi
    else
        echo -e "${level}%"
    fi
fi
