#! /usr/bin/env bash

# setup - system setup script for macOS
# =========================================================
# - https://github.com/danishprakash/dotfiles
# - danishpraka.sh

# variables
DOT_DIR = ~/dotfiles

# install brew
echo "--> Installing homebrew..."
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# cli
echo "--> Installing applications..."
brew install zsh
brew install tmux
brew install tree
brew install neovim
brew install python
brew install python3
brew install zsh-completions
brew install zsh-autosuggestions
brew install zsh-syntax-highlighting
brew install rg
brew install ctags
brew install fzf
brew install jq

brew tap homebrew/cask

brew cask install slack
brew cask install iina
brew cask install iterm2
brew cask install spotify
brew cask install firefox
brew cask install lastpass
brew cask install tunnelbear
brew cask install transmission
